### ISSUE TITLE
SS or SS+DNA

### ISSUE THREAD

**Issue by Lordhooze** [HAN-Siyu/LncFinder#3]
Dear siyu Han:
    Recently I used LncFinder to predicted LncRNA genes. however, I got a question. I build the model using my own mRNA and LncRNA data. I run  "lncFinder" with  format = "SS", features = TRUE. Should I run  "lncFinder" with format="DNA" and  features=FALSE again? should I overlap the results generated by these two steps?

Thank you very much

**Comment by HAN-Siyu** [comment]
Hi @Lordhooze , thanks for using LncFinder. The `format` argument (`"SS"` or `"DNA"`) indicates whether the secondary structural information will be used to predict the input sequences. We provide `"DNA"` option mainly because sometimes structural information may not be available or may be very time-consuming to calculate/obtain. 

Based on our experiments and other independent reviews, seems that `"SS"` (using secondary structural features) could yield better results than `"DNA"`. If you would like to use LncFinder to predict some unknown genes, it may be not necessary to compute results from both options. 

Hope this helps.

**Comment by HAN-Siyu** [comment]
> Dear siyu Han: Recently I used LncFinder to predicted LncRNA genes. however, I got a question. I build the model using my own mRNA and LncRNA data. I run "lncFinder" with format = "SS", features = TRUE. Should I run "lncFinder" with format="DNA" and features=FALSE again? should I overlap the results generated by these two steps?
> 
> Thank you very much

Hi @Lordhooze , thanks for using LncFinder. The format argument ("SS" or "DNA") indicates whether the secondary structural information will be used to predict the input sequences. We provide "DNA" option mainly because sometimes structural information may not be available or may be very time-consuming to calculate/obtain.

Based on our experiments and other independent reviews, seems that "SS" (using secondary structural features) could yield better results than "DNA". If you would like to use LncFinder to predict some unknown genes, it may be not necessary to compute results from both options.

Hope this helps.
